### PR TITLE
Add Hero - Minus search functionality

### LINKED ISSUE #4: Update Hero
Search - Homes/Agents

Homes/Agents/Offices

Title Only - (Which is optional)
title_only

### PR DESCRIPTION
**Pull request by bstopp**
Fix #4 

Test URLs:
- After: https://feat-hero--hsf-commonmoves--hlxsites.hlx.page/drafts/stopp/hero-no-text

- After: https://feat-hero--hsf-commonmoves--hlxsites.hlx.page/drafts/stopp/hero

- After: https://feat-hero--hsf-commonmoves--hlxsites.hlx.page/drafts/stopp/hero-no-search

- After: https://feat-hero--hsf-commonmoves--hlxsites.hlx.page/drafts/stopp/communities/acton

### CODE REVIEW

**Comment by irenelagno** [comment]
A couple of minor UI issues:
-remove outline on focus for input
- search input alignment and header are not the same
- navigation logo is  smaller than on original website
PR version
Screen Shot 2023-04-14 at 4 36 01 PM
original website
Screen Shot 2023-04-14 at 4 35 46 PM

**Review by irenelagno — APPROVED** [review]
Please fix minor UI issues and countries list on next PR

**Comment by bstopp** [comment]
All of these visual changes were intentional, not a miss.

**Comment by irenelagno** [comment]
Styling issue for country drop-down:
Screen Shot 2023-04-17 at 3 38 24 PM

placeholder for input should be "Enter City" for non US countries.

**Review by irenelagno — APPROVED** [review]

**Comment by irenelagno** [comment]
Agreed to fix issue with closing country filter in the next PR

**Pull request merged**
